baseURL = "https://dsrca.amzrk2.cc"
languageCode = "zh-hans"
title = "DSRCA"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
googleAnalytics = "UA-146011233-7"

[params]
  author = "DSRKafuU"
  description = "DSRCA home."
  images = ["https://dsrca.amzrk2.cc/img/og.png"]
